# -*- coding: utf-8 -*-
"""Cliente.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f8Voc3Qor4SSJw854VEA8vJnPQdADG7-
"""

class Cliente:
    def __init__(self, nombre, cuenta, fechaNac):
        self.nombre = nombre
        self.cuenta = (cuenta)
        self.fechaNac = fechaNac

    def informacion(self):
        print("Nombre: ", self.nombre)
        self.cuenta.impInfo()
        print("Fecha de Nacimiento: ", self.fechaNac)