# -*- coding: utf-8 -*-
"""Cuenta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kdPmuFtJx4KMVVdRqy4ND_s7-AOPfngv
"""

class Cuenta:
  def __init__(self, tipo, valor ,fecha):
    self.tipo = tipo
    self.valor = float(valor)
    self.fecha = fecha

  def impInfo(self):
    print("Tipo de la cuenta: ", self.tipo)
    print("Saldo de la cuenta: ", self.valor)
    print("Fecha de Contratación: ", self.fecha)
    return

  def retirar(self, cantidad):
    self.valor = self.valor - cantidad

  def depositar(self, cantidad):
    if cantidad > 0 :
      self.valor = self.valor + cantidad
      return True
    else:
      return False

  def __str__(self):
    return "saldo :: " + str(self.valor) + " | tipo :: " + self.tipo