# -*- coding: utf-8 -*-
"""Inventario 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EKyLwrja2shqsIKTKpWLryUx4ShQwwHq
"""

# Cruz Barrón

class Producto:
    def __init__(self, nombre, cantidad, precio):
        self.nombre = nombre
        self.cantidad = cantidad
        self.precio = precio

    def __str__(self):
        return f"{self.nombre} | Stock: {self.cantidad} | Precio: ${self.precio}"

    def agregar_stock(self, cantidad):
        self.cantidad += cantidad

    def vender(self, cantidad):
        self.cantidad -= cantidad


class Departamento:
    def __init__(self, nombre_depa, nombre_prod, cant_prod, precio_prod):
        self.nombre_depa = nombre_depa

        # Composición estricta: Departamento crea y es dueño del Producto
        self.producto_asignado = Producto(nombre_prod, cant_prod, precio_prod)

    def __str__(self):
        return f"Departamento: {self.nombre_depa.upper()} -> Inventario: [{self.producto_asignado}]"

    def agregar_stock(self, cantidad):
        self.producto_asignado.agregar_stock(cantidad)

    def reducir_stock(self, cantidad):
        self.producto_asignado.vender(cantidad)

#VALIDACIONES EN BOLEANO
def validar_ingreso(cantidad):
    """Verifica que la cantidad a ingresar sea un número positivo."""
    return cantidad > 0

def validar_venta(cantidad, stock_actual):
    """Verifica que la cantidad sea positiva y no supere el stock disponible."""
    return cantidad > 0 and cantidad <= stock_actual

#  INTERFAZ DE USUARIO (VISTA/CONTROLADOR)

class Menu:
    def __init__(self):
        # El menú instancia el Departamento y sus atributos al arrancar
        self.depa = Departamento("Juvenil", "chamarra_cuero", 15, 2500)

    def iniciar(self):
        while True:
            print("\n" + "×"*50)
            print(f"   {self.depa}   ")
            print("≈"*50)
            print("1. Ver inventario")
            print("2. Recibir mercancía (Agregar stock)")
            print("3. Realizar venta (Retirar stock)")
            print("4. Salir")

            opcion = input("\nElige una opción (1-4): ")
            prod = self.depa.producto_asignado

            if opcion == '1':
                print(f"\n📦 Producto: {prod.nombre} | Stock: {prod.cantidad} | Precio: ${prod.precio}")

            elif opcion == '2':
                cantidad = int(input("¿Cuántas unidades llegaron?: "))

                # ---> USAMOS LA SECCIÓN DE VALIDACIONES <---
                if validar_ingreso(cantidad):
                    self.depa.agregar_stock(cantidad)
                    print(f"✅ ¡Stock actualizado! Ahora hay {prod.cantidad} unidades disponibles.")
                else:
                    print("❌ Error: La cantidad a agregar debe ser mayor a cero.")

            elif opcion == '3':
                cantidad = int(input("¿Cuántas unidades vas a vender?: "))

                # ---> USAMOS LA SECCIÓN DE VALIDACIONES <---
                # Le enviamos la cantidad pedida y el stock que hay actualmente
                if validar_venta(cantidad, prod.cantidad):
                    self.depa.reducir_stock(cantidad)
                    print(f"✅ ¡Venta exitosa! Quedan {prod.cantidad} unidades en inventario.")
                else:
                    print("❌ Error: Stock insuficiente o cantidad inválida.")

            elif opcion == '4':
                print("\nCerrando el sistema... ¡Buen día!")
                break

            else:
                print("\n⚠️ Opción no válida.")

# 4. EJECUCIÓN DEL PROGRAMA
if __name__ == "__main__":
    app_menu = Menu()
    app_menu.iniciar()