# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MLJWho4KRQQR0HwlpCrzNTFPurytOYpi
"""

# --- CÓDIGO 1: DEFINICIONES DE CLASES ---

class Producto:
    def __init__(self, nombre, cantidad, precio):
        self.nombre = nombre
        self.cantidad = cantidad
        self.precio = precio

# CLASE COMPUESTA
class Departamento:
    def __init__(self, nombre_depa, producto_p):
        self.nombre_depa = nombre_depa
        # COMPOSICIÓN: El atributo es un objeto de la clase Producto
        self.producto_asignado = producto_p

    def agregar_stock(self, cantidad):
        self.producto_asignado.cantidad += cantidad

    def reducir_stock(self, cantidad):
        self.producto_asignado.cantidad -= cantidad

# --- CÓDIGO 2: VALIDACIONES ---

def es_venta_valida(Departamento, cantidad_a_vender):
    """Verifica que no se venda más de lo que hay en stock y que no sean negativos."""
    if cantidad_a_vender <= 0:
        print("❌ Error: Debes ingresar una cantidad mayor a cero.")
        return False

    # Accedemos al stock a través de la clase compuesta: tienda -> producto -> cantidad
    stock_actual = Departamento.producto_asignado.cantidad

    if cantidad_a_vender > stock_actual:
        print(f"❌ Error: Stock insuficiente. Solo tienes {stock_actual} unidades.")
        return False

    return True

def es_ingreso_valido(cantidad_a_agregar):
    """Verifica que no se ingresen cantidades ilógicas al stock."""
    if cantidad_a_agregar <= 0:
        print("❌ Error: La cantidad a agregar debe ser mayor a cero.")
        return False
    return True

# --- MENÚ INTERACTIVO ---

mi_producto = Producto("chamarra_cuero", 15, 2500)

# Objeto Departamento, pasándole el Producto (Composición)
Depa = Departamento("Juvenil", mi_producto)

while True:
    print("\n" + "×"*40)
    print(f"   Departamento: {Depa.nombre_depa.upper()}   ")
    print("≈"*40)
    print("1. Ver inventario")
    print("2. Recibir mercancía (Agregar stock)")
    print("3. Realizar venta (Retirar stock)")
    print("4. Salir")

    opcion = input("\nElige una opción (1-4): ")

    if opcion == '1':

        prod = Depa.producto_asignado
        print(f"\n📦 Producto: {prod.nombre} | Stock: {prod.cantidad} | Precio: ${prod.precio}")
    elif opcion == '2':
        cantidad = int(input("¿Cuántas unidades llegaron?: "))
        if es_ingreso_valido(cantidad):
            Depa.agregar_stock(cantidad)

            stock_actual = Depa.producto_asignado.cantidad
            print(f"✅ ¡Stock actualizado! Ahora hay {stock_actual} unidades disponibles.")

    elif opcion == '3':
        cantidad = int(input("¿Cuántas unidades vas a vender?: "))
        if es_venta_valida(mi_tienda, cantidad):
            Depa.reducir_stock(cantidad)

            stock_actual = Depa.producto_asignado.cantidad
            print(f"✅ ¡Venta exitosa! Quedan {stock_actual} unidades en inventario.")
    elif opcion == '4':
        print("\nCerrando el sistema... ¡Buen día!")
        break

    else:
        print("\n⚠️ Opción no válida.")