# -*- coding: utf-8 -*-
"""Inventario.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uOiSu9C0GM1aS3O7Sc6YGwibQLbQX8GO

Inventario
"""

#correr primero este porque de lo contrario me da error (quiza es obvio pero yo me espante por que no corria)
class Producto:
  def __init__(self, nombre_producto, cantidad_inicial, precio_unitario):
     self.nombre = nombre_producto      # Atributo 1
     self.cantidad = cantidad_inicial   # Atributo 2
     self.precio = precio_unitario      # Atributo 3

  # Método 1: Equivalente a "depositar"
  def agregar_stock(self, cantidad_a_agregar):
      self.cantidad = self.cantidad + cantidad_a_agregar

  def vender(self, cantidad_a_vender):
      if cantidad_a_vender <= self.cantidad:
        self.cantidad = self.cantidad - cantidad_a_vender
      else:
        print("Error: No hay suficiente stock para vender esa cantidad.")

# menu del inventario
producto1 = Producto("chamarra_negra_piel", 1, 300)
print("Probando el objeto Producto")
producto1 = Producto("chamarra_negra_piel", 0, 300)

print("Agregando 1 chamarra  al inventario...")
producto1.agregar_stock(1)

print("Vendiendo 1 chamarra...")
producto1.vender(2)

print("\n--- Resultados Finales ---")
print("Producto: ", producto1.nombre)
print("Stock disponible: ", producto1.cantidad)
print("Precio unitario: $", producto1.precio)