# -*- coding: utf-8 -*-
"""PruebasMenu inventario

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ofmlBplPWqlO3a4NTb58vAA44D_Fsxa

Menu
"""

class Producto:
    def __init__(self, nombre_producto, cantidad_inicial, precio_unitario):
        self.nombre = nombre_producto
        self.cantidad = cantidad_inicial
        self.precio = precio_unitario

    def agregar_stock(self, cantidad_a_agregar):
        self.cantidad = self.cantidad + cantidad_a_agregar
        print(f"Se agregaron {cantidad_a_agregar}. Nuevo stock: {self.cantidad}")

    def vender(self, cantidad_a_vender):
        if cantidad_a_vender <= self.cantidad:
            self.cantidad = self.cantidad - cantidad_a_vender
            print(f"Se vendieron {cantidad_a_vender}. Nuevo stock: {self.cantidad}")
        else:
            print("Error: No hay suficiente stock para vender esa cantidad.")

producto1 = Producto("chamarra_negra_cuero", 2, 300)

# Menú Interactivo
while True:
    print("\n" + "="*30)
    print("      MENÚ DE INVENTARIO      ")
    print("="*30)
    print("1. Consultar estado del producto")
    print("2. Agregar stock ")
    print("3. Vender")
    print("4. Salir")
    print("="*30)

    # Le pedimos al usuario que ingrese un número
    opcion = input("Ingresa el número de la acción que deseas realizar: ")

    if opcion == '1':
        print(f"\n--- Detalles ---")
        print(f"Producto: {producto1.nombre}")
        print(f"Stock actual: {producto1.cantidad} unidades")
        print(f"Precio: ${producto1.precio}")

    elif opcion == '2':
        # Pedimos la cantidad
        cantidad_ingresada = int(input("\n¿Cuántas unidades vas a agregar?: "))
        mi_producto.agregar_stock(cantidad_ingresada)

    elif opcion == '3':
        cantidad_ingresada = int(input("\n¿Cuántas unidades vas a vender?: "))
        mi_producto.vender(cantidad_ingresada)

    elif opcion == '4':
        print("\nSaliendo del sistema de inventario... ¡Hasta luego!")
        break

    else:
        print("\nOpción no válida. Por favor, ingresa un número del 1 al 4.")